## map:
## spacing is how many blocks apart each particle is
## '{number}' is how many blocks in front or behind the following rows are#
##
## sound: 
## sound enums: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
## 1st float: volume
## 2nd float: pitch
## 3rd float: how many ticks to wait

effects:
  test1:
    name: 'Test'
    pitch: true
    sounds:
      - 'BLOCK_NOTE_PLING;1;1.50;1'
      - 'BLOCK_NOTE_PLING;1;1.55;2'
      - 'BLOCK_NOTE_PLING;1;1.60;3'
      - 'BLOCK_NOTE_PLING;1;1.65;4'
      - 'BLOCK_NOTE_PLING;1;1.70;5'
      - 'BLOCK_NOTE_PLING;1;1.75;6'
      - 'BLOCK_NOTE_PLING;1;1.80;7'
      - 'BLOCK_NOTE_PLING;1;1.85;8'
      - 'BLOCK_NOTE_PLING;1;1.90;9'
      - 'BLOCK_NOTE_PLING;1;1.95;10'
      - 'BLOCK_NOTE_PLING;1;1.90;11'
      - 'BLOCK_NOTE_PLING;1;1.85;12'
      - 'BLOCK_NOTE_PLING;1;1.80;13'
      - 'BLOCK_NOTE_PLING;1;1.85;14'
      - 'BLOCK_NOTE_PLING;1;1.80;15'
      - 'BLOCK_NOTE_PLING;1;1.75;16'
      - 'BLOCK_NOTE_PLING;1;1.70;17'
      - 'BLOCK_NOTE_PLING;1;1.65;18'
      - 'BLOCK_NOTE_PLING;1;1.60;19'
      - 'BLOCK_NOTE_PLING;1;1.55;20'
      - 'BLOCK_NOTE_PLING;1;1.60;21'
      - 'BLOCK_NOTE_PLING;1;1.65;22'
      - 'BLOCK_NOTE_PLING;1;1.70;23'
      - 'BLOCK_NOTE_PLING;1;1.75;24'
      - 'BLOCK_NOTE_PLING;1;1.80;25'
      - 'BLOCK_NOTE_PLING;1;1.85;26'
      - 'BLOCK_NOTE_PLING;1;1.90;27'
      - 'BLOCK_NOTE_PLING;1;1.95;28'
      - 'BLOCK_NOTE_PLING;1;1.90;29'
      - 'BLOCK_NOTE_PLING;1;1.85;30'
      - 'BLOCK_NOTE_PLING;1;1.80;31'
      - 'BLOCK_NOTE_PLING;1;1.85;32'
      - 'BLOCK_NOTE_PLING;1;1.80;33'
      - 'BLOCK_NOTE_PLING;1;1.75;34'
      - 'BLOCK_NOTE_PLING;1;1.70;35'
      - 'BLOCK_NOTE_PLING;1;1.65;36'
      - 'BLOCK_NOTE_PLING;1;1.60;37'
      - 'BLOCK_NOTE_PLING;1;1.55;38'
    spacing: .35
    map:
      - '{0}'
      - '.AA.A.AA.'
      - 'AAAAAAAAA'
      - 'AAAAAAAAA'
      - '.AAAAAAA.'
      - '...AAA...'
      - '....A....'
      - '....P....'
  test2:
    name: 'test2'
    sounds:
      - 'RECORD_STAL;1;0.07;0'
      - 'RECORD_STAL;1;0.07;0'
      - 'RECORD_STAL;1;0.07;0'
      - 'RECORD_STAL;1;0.07;0'
    spacing: .3
    map:
      - '{0}'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '........P.........'
  test3:
    name: 'test3'
    spacing: .3
    map:
      - '{0}'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '........P.........'
      - '{4}'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
      - '{-8}'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
      - '..AA..AA..AA..AA..'
      - '..AA..AA..AA..AA..'
      - '..................'
      - '..................'
      - '..................'
  hello:
    name: 'hello'
    spacing: .3
    map:
      - '{0}'
      - '.A..A..AAA..A....A....AAAA.'
      - '.A..A..A....A....A....A..A.'
      - '.AAAA..AAA..A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..AAA..AAA..AAA..AAAA.'
      - '.............P.............'
  hello2:
    name: 'hello2'
    spacing: .3
    map:
      - '{0}'
      - '.A..A..AAA..A....A....AAAA.'
      - '.A..A..A....A....A....A..A.'
      - '.AAAA..AAA..A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..AAA..AAA..AAA..AAAA.'
      - '.............P.............'
      - '{-20}'
      - '.A..A..AAA..A....A....AAAA.'
      - '.A..A..A....A....A....A..A.'
      - '.AAAA..AAA..A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..AAA..AAA..AAA..AAAA.'
      - '...........................'
      - '{20}'
      - '.A..A..AAA..A....A....AAAA.'
      - '.A..A..A....A....A....A..A.'
      - '.AAAA..AAA..A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..A....A....A....A..A.'
      - '.A..A..AAA..AAA..AAA..AAAA.'
      - '...........................'
  box:
    name: 'box'
    spacing: .5
    map:
      - '{0}'
      - '..AAA..'
      - '..APA..'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '{-1}'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '{1}'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
      - '..AAA..'
  test5:
    name: 'test5'
    spacing: .3
    map:
      - '{0}'
      - '...B.B....'
      - '.B.....B..'
      - 'CCCCCCCCC.'
      - 'BCCCCCCCB.'
      - '..CCPCC...'