## # #  # # ##
##  Powder  ##
## # #  # # ##

## Current version of this config.yml. Should not be edited.
configVersion: 1

## Maximum amount of Powders that a user can be using at one time
maxPowdersAtOneTime: 3

## If true, users can use the same Powder multiple times at once
allowSamePowdersAtOneTime: true

## Minimum time allowed between usage of Powders
secondsBetweenPowderUsage: 5

## Powders per page in any formatted list
## (/powder help, /powder list, etc)
pageLength: 7

## If true, the console will send a list of all Powders loaded on startup/reload
listOfLoadedPowders: true

## If true, Powders are divided into categories
categoriesEnabled: true

## List of categories
## {total} -- Number of Powders in this category
## {total-hidden} -- Number of unhidden Powders in this category
categories:
  Emojis:
    desc: '{total} Emojis'
  Flags:
    desc: '{total} Flags of Countries'
  Effects:
    desc: '{total} Random Particles / Effects'
  Songs:
    desc: '{total} Songs with Effects'
  Crowns:
    desc: '{total} Particles Around your Head'

## Use storage to continue Powders between each server or after logout
## If disabled, Powders attached to entities will unload alongside chunk unloading
storage:
  mysql:
    use: false
    host: localhost
    port: 3306
    database: minecraft
    table: powders
    username: root
    password: password

## Locale to use (from locale source folder)
locale: 'en-us.yml'

## Files/URLs to source Powder configuration files from
powderSources:
  - 'powders.yml'