main: ${mainClass}
name: ${name}
version: ${version}
authors: [StupidDrew9, royalkingkb]
commands: 
  powder:
    aliases: [pow, pdr, powders]
permissions:
  powder.reload:
    default: op
    description: Allow usage of /powder reload
  powder.command:
    default: false
    description: Allow usage of /powder
  powder.powder.*:
    default: false
    description: Allows usage of all available Powders