# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - build.*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "github-towny", "username": "Kas-tle", "password": "${GITHUB_TOKEN}"}]'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Powder-Latest
        path: staging/Powder-*.jar
    - name: Generate release diff
      env:
        BEGIN_COMMIT: ${{ steps.version.outputs.previous_tag }}
        END_COMMIT: ${{ steps.version.outputs.tag }}
      run: git log --all --graph --oneline ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.txt
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: staging/Powder-*.jar
        bodyFile: release_notes.txt
        token: ${{ secrets.GITHUB_TOKEN }}
