# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: setup-maven-settings
        uses: s4u/maven-settings-action@v1
        with:
          servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

      - name: checkout
        uses: actions/checkout@v1

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -Dmaven.wagon.http.pool=false clean package
